### PR TITLE
Resolve Issue #80 rval cstring fixes

### LINKED ISSUE #80: C-Strings Passed as R-Value Arguments Incorrectly
Tried to see how codegen worked with some c-style strings and found this issue:

This code:
`int puts(char* str);
int main()
{
    puts("Hello, world!");
    return 0;
}`

Yields this output:
`declare i32 @puts(i8 %str)
define i32 @main()
{
    %t_0 = call i32 @puts(i8* Hello, world!)
    ret i32 0
}`

As you can see, the argument will clearly not be accepted by Clang/LLVM and it doesn't.

### PR DESCRIPTION
**Pull request by hockeyhurd**
PR for resolving issue mentioned in issue #80.

### CODE REVIEW

**Comment by hockeyhurd** [comment]
To note, while resolving this issue, I stumbled upon a related issue.

LitteralNodes will internally mark c-strings using the EnumCType::STRING enumeration.
In contrast a VariableDeclarationNode will parse `char* c;` as a EnumCType::CHAR, but a '1' in the pointer field of the CType (the outer structure where the EnumCType field is stored).

I will be writing a new issue to cover this as to not unnecessarily expand the scope of this PR's issue.

**Comment by hockeyhurd** [comment]
> LitteralNodes will internally mark c-strings using the EnumCType::STRING enumeration.
> In contrast a VariableDeclarationNode will parse `char* c;` as a EnumCType::CHAR, but a '1' in the pointer field of the CType (the outer structure where the EnumCType field is stored).

Created issue #82 for this.

File: src/platform/PlatformLLVM.cpp [hunk 1]
```diff
@@ -429,6 +432,19 @@ namespace cmm
     {
         static auto& reporter = Reporter::instance();
 
+        static auto assembleCString = [](const std::string& key, const std::string& value) -> std::string
+        {
+            // For reference: noundef getelementptr inbounds ([14 x i8], [14 x i8]* @.str
```
Comment (hockeyhurd) [inline src/platform/PlatformLLVM.cpp]: Can remove

File: src/platform/PlatformLLVM.cpp [hunk 2]
```diff
@@ -578,6 +601,53 @@ namespace cmm
...
+
+            for (auto& [key, value] : stringLitteralTable)
+            {
+                // Override the name for future LitteralNode lookups
+                value = genStringName();
+
+                // +1 for null termination character
+                const std::size_t strSize = key.size() + 1;
+                os << "@" << value << " = private unnamed_addr constant [" << strSize << " x i8] c\""
+                    << key << "\\00\", align 1";
```
Comment (hockeyhurd) [inline src/platform/PlatformLLVM.cpp]: Nitpick: align spacing

**Review by hockeyhurd — COMMENTED** [review]
See review comments.
