### PR TITLE
Branch hurdn_feat update to dev

### LINKED ISSUE #66: LLVM Generated 'ptr' Usage Incompatible with Clang 14 and Older
Using this code:

`struct Vec2
{
    int x;
    int y;
};
int func(void)
{
    struct Vec2 v2;
    v2.x = 10;
    v2.y = 32;
    int sum;
    sum = v2.x + v2.y;
    return sum;`

Generates this:

`define i32 @main()
{
    %v2 = alloca %struct.Vec2
    %t_0 = getelementptr inbounds %struct.Vec2, ptr %v2, i32 0, i32 0
    store i32 10, i32* %t_0
    %t_1 = getelementptr inbounds %struct.Vec2, ptr %v2, i32 0, i32 1
    store i32 32, i32* %t_1
    %result = alloca i32
    %t_2 = getelementptr inbounds %struct.Vec2, ptr %v2, i32 0, i32 1
    %t_3 = load i32, i32* %t_2
    %t_4 = getelementptr inbounds %struct.Vec2, ptr %v2, i32 0, i32 0
    %t_5 = load i32, i32* %t_4
    %t_6 = add i32 %t_5, %t_3
    store i32 %t_6, i32* %result
    %t_7 = load i32, i32* %result
    ret i32 %t_7
}`

Which creates the error:

`Test.ll:7:53: error: '%v2' defined with type '%struct.Vec2*' but expected 'ptr'`

The proposed solution is to fallback on the older format for backwards compatibility.

### PR DESCRIPTION
**Pull request by hockeyhurd**
A few highlights:

- Field access from a struct variable now supported.
- Resolved some cppcheck warnings and errors
- Issue #66 resolved

### CODE REVIEW

File: include/cmm/Field.h [hunk 1]
```diff
@@ -0,0 +1,132 @@
...
+         * Sets this Field based upon another's IField.
+         *
+         * @param other the other IField to set from.
+         *        Note: This parameter shall ALWAYS be a valid pointer.
+         */
+        void set(const IField* other) override;
+
+    private:
+
+        std::string name;
```
Comment (hockeyhurd) [inline include/cmm/Field.h:133]: Add a quick comment to these variables.

File: include/cmm/StructDefinitionStatementNode.h [hunk 2]
```diff
@@ -13,15 +13,24 @@
...
 #include <string>
+#include <unordered_map>
 
 namespace cmm
 {
     class StructDefinitionStatementNode : public StatementNode
     {
+    public:
+
+        using FieldMap = std::unordered_map<std::string, Field>;
```
Comment (hockeyhurd) [inline include/cmm/StructDefinitionStatementNode.h:30]: Consider using new the IField interface.

File: include/cmm/StructTable.h [hunk 3]
```diff
@@ -12,19 +12,50 @@
...
-#include <optional>
 #include <string>
 #include <unordered_map>
 
 namespace cmm
 {
+    struct StructData
+    {
+        EnumSymState symState;
+        std::unordered_map<std::string, Field> fieldMap;
```
Comment (hockeyhurd) [inline include/cmm/StructTable.h:26]: Consider using the new IField interface.

File: include/cmm/platform/PlatformBase.h [hunk 4]
```diff
@@ -123,6 +123,7 @@ namespace cmm
         virtual std::optional<VisitorResult> emit(Encode* encoder, BinOpNode& node, const VisitorResult& left, const VisitorResult& right) = 0;
         virtual std::optional<VisitorResult> emit(Encode* encoder, CastNode& node, const VisitorResult& expr) = 0;
         virtual std::optional<VisitorResult> emit(Encode* encoder, DerefNode& node, const VisitorResult& varResult) = 0;
+        virtual std::optional<VisitorResult> emit(Encode* encoder, FieldAccessNode& node, VisitorResult&& expr) = 0;
```
Comment (hockeyhurd) [inline include/cmm/platform/PlatformBase.h]: Unnecessary move, can probably pass by const reference.

File: include/cmm/platform/PlatformLLVM.h [hunk 5]
```diff
@@ -72,6 +72,7 @@ namespace cmm
         virtual std::optional<VisitorResult> emit(Encode* encoder, BinOpNode& node, const VisitorResult& left, const VisitorResult& right) override;
         virtual std::optional<VisitorResult> emit(Encode* encoder, CastNode& node, const VisitorResult& expr) override;
         virtual std::optional<VisitorResult> emit(Encode* encoder, DerefNode& node, const VisitorResult& varResult) override;
+        virtual std::optional<VisitorResult> emit(Encode* encoder, FieldAccessNode& node, VisitorResult&& expr) override;
```
Comment (hockeyhurd) [inline include/cmm/platform/PlatformLLVM.h]: Unnecessary move, can probably pass by const reference.

File: src/Parser.cpp [hunk 6]
```diff
@@ -20,6 +20,7 @@
 #include <iostream>
 #include <optional>
 #include <sstream>
+#include <utility>
```
Comment (hockeyhurd) [inline src/Parser.cpp:23]: Confirm this is needed (I forgot why I added this)?

File: src/Parser.cpp [hunk 7]
```diff
@@ -1461,7 +1494,8 @@ namespace cmm
         case TokenType::SYMBOL:
             // We need to restore because 'parseFunctionCallOrVariable' with consume the token for us...
             lexer.restore(snapshot);
-            return parseFunctionCallOrVariable(lexer, errorMessage);
+            // return parseFunctionCallOrVariable(lexer, errorMessage);
```
Comment (hockeyhurd) [inline src/Parser.cpp]: Remove dead (commented) code.

File: src/StructDefinitionStatementNode.cpp [hunk 8]
```diff
@@ -44,6 +45,54 @@ namespace cmm
...
 
+    std::optional<std::string> StructDefinitionStatementNode::setupFieldTable()
+    {
+        // Only re/calculate if the fieldMap is empty.
+        if (!fieldMap.empty())
+        {
+            return std::nullopt;
+        }
+
+        u32 index = 0;
```
Comment (hockeyhurd) [inline src/StructDefinitionStatementNode.cpp]: Field class and/or IField use s32 so that they can use '-1' to indicate "not yet defined".  Consider making this a s32 for consistency.

File: src/StructTable.cpp [hunk 9]
```diff
@@ -10,6 +10,23 @@
 
 namespace cmm
 {
+    StructData::StructData(const EnumSymState symState, std::unordered_map<std::string, Field>&& fieldMap) :
+        symState(symState), fieldMap(std::move(fieldMap))
+    {
+    }
+
+    Field* StructData::findField(const std::string& name) CMM_NOEXCEPT
```
Comment (hockeyhurd) [inline src/StructTable.cpp]: Consider using the IField interface.

File: src/StructTable.cpp [hunk 10]
```diff
@@ -10,6 +10,23 @@
...
+    {
+        const auto findResult = fieldMap.find(name);
+        return findResult != fieldMap.cend() ? &findResult->second : nullptr;
+    }
+
+    const Field* StructData::findField(const std::string& name) const CMM_NOEXCEPT
```
Comment (hockeyhurd) [inline src/StructTable.cpp]: Consider using the IField interface.

File: src/visit/Analyzer.cpp [hunk 11]
```diff
@@ -795,7 +902,9 @@ namespace cmm
         auto* expression = node.getExpression();
         expression->accept(this);
 
-        if (expression->getType() == EnumNodeType::VARIABLE)
+        // TODO: Test with this for now... revisit once confirm through more testing...
```
Comment (hockeyhurd) [inline src/visit/Analyzer.cpp]: Resolve TODO.

File: src/visit/Analyzer.cpp [hunk 12]
```diff
@@ -810,19 +919,41 @@ namespace cmm
...
+            {
+                std::ostringstream builder;
+                builder << "Found duplicate field in struct '" << node.getName() << "' called '"
+                        << *optionalBadField << "'";
+                reporter.error(builder.str(), node.getLocation());
+            }
+
+            // Copy StructDefinitionStatementNode FieldMap to here so that we
+            // have a copy in the StructTable.
+            // TODO: Try to reduce unnecessary copying in the future.
```
Comment (hockeyhurd) [inline src/visit/Analyzer.cpp:945]: Do we want to resolve this now?

File: src/visit/Dump.cpp [hunk 13]
```diff
@@ -152,6 +152,26 @@ namespace cmm
         return VisitorResult();
     }
 
+    VisitorResult Dump::visit(FieldAccessNode& node)
+    {
+        // TODO @@@: Anything to update due to recent changes??
```
Comment (hockeyhurd) [inline src/visit/Dump.cpp]: Finish TODO or remove.

**Review by hockeyhurd — COMMENTED** [review]
Looks good, just a few things to resolve/clean-up.

File: src/visit/Analyzer.cpp (hunk 12 above)
Comment (hockeyhurd) [reply src/visit/Analyzer.cpp:945]: This would require re-thinking how the StructTable is used.  More specifically and in the current state, StructTable is only used in the Analyzer and not in the Encoder.  This would mean we would need to somehow make the StructTable visible to all of the current translation unit (only).  This sounds like a bigger change than what I want to include in this PR.  Will create a new issue, link it to here, and close this comment for resolution.

File: src/visit/Analyzer.cpp (hunk 11 above)
Comment (hockeyhurd) [reply src/visit/Analyzer.cpp]: Resolved in commit '7f506c12752d530b27bc0bf13b7b29fb4220e760'.

File: include/cmm/Field.h (hunk 1 above)
Comment (hockeyhurd) [reply include/cmm/Field.h:133]: Resolved in commit '8f3adcc6aca4f7e829d4d2d565f9df9c17e25dfd'.

File: include/cmm/platform/PlatformLLVM.h (hunk 5 above)
Comment (hockeyhurd) [reply include/cmm/platform/PlatformLLVM.h]: Resolved in commit 'f1b5ef2ef900b357d9fdb290d8b5c1240f2d40b9'.

File: include/cmm/platform/PlatformBase.h (hunk 4 above)
Comment (hockeyhurd) [reply include/cmm/platform/PlatformBase.h]: Resolved in commit 'f1b5ef2ef900b357d9fdb290d8b5c1240f2d40b9'.

File: src/visit/Analyzer.cpp (hunk 12 above)
Comment (hockeyhurd) [reply src/visit/Analyzer.cpp:945]: Created issue #69 for tracking this issue/enhancement.  This is considered resolved for this review.

File: src/visit/Dump.cpp (hunk 13 above)
Comment (hockeyhurd) [reply src/visit/Dump.cpp]: Resolved in commit '7da05acf76976651f8f5bc5c7a9f4298f04d6f9b'.

File: src/Parser.cpp (hunk 6 above)
Comment (hockeyhurd) [reply src/Parser.cpp:23]: Compiles without this include. However, according to cppreference, this include provides, among other things, std::move. Keeping this include for this reason in case a different platform needs this.

File: src/Parser.cpp (hunk 7 above)
Comment (hockeyhurd) [reply src/Parser.cpp]: Resolved in commit '2c95939e53a118eef5d280d641c93783fc93dabf'.

File: include/cmm/StructDefinitionStatementNode.h (hunk 2 above)
Comment (hockeyhurd) [reply include/cmm/StructDefinitionStatementNode.h:30]: After reviewing the code, I decided to keep as-is to avoid needing to do extra heap allocation.  Any 'getter' type functions will instead use IField, but keep this storage as a "normal" Field.

File: src/StructTable.cpp (hunk 9 above)
Comment (hockeyhurd) [reply src/StructTable.cpp]: After reviewing the code, I decided to keep as-is to avoid needing to do extra heap allocation.  Any 'getter' type functions will instead use IField, but keep this storage as a "normal" Field.

File: src/StructTable.cpp (hunk 10 above)
Comment (hockeyhurd) [reply src/StructTable.cpp]: Resolved in commit 'f7899b3bcb6b2f7f852dcc3bcfab21407dc03d54'.

File: src/StructDefinitionStatementNode.cpp (hunk 8 above)
Comment (hockeyhurd) [reply src/StructDefinitionStatementNode.cpp]: Resolved in commit 'f7899b3bcb6b2f7f852dcc3bcfab21407dc03d54'.

File: include/cmm/StructTable.h (hunk 3 above)
Comment (hockeyhurd) [reply include/cmm/StructTable.h:26]: After reviewing the code, I decided to keep as-is to avoid needing to do extra heap allocation. Any 'getter' type functions will instead use IField, but keep this storage as a "normal" Field.

**Comment by hockeyhurd** [comment]
Did some manual testing across Linux, FreeBS, etc. and architectures x86_64 and ARMv7(hf) and saw no issues.  Merging to dev.
