### PR TITLE
Resolve issue #76 - unnecessary castnode

### LINKED ISSUE #76: Unnecessary CastNode Causes Illegal LLVM Opcode
A simple example:
`int main()
{
  int z;
  z = (int) 5;
  return z;
}`

Result: "Test.ll:4:12: error: expected instruction opcode"

### PR DESCRIPTION
**Pull request by hockeyhurd**
This PR resolves the problem described in issue #76.  While working on the issue, I noticed a few other casts were in properly being handled.  For example, downcasting/narrowing from int to char should emit ztrunc instruction (LLVM) and inversely emit a zext instruction (LLVM) when upcasting/widening.

### CODE REVIEW

File: src/VariableNode.cpp [hunk 1]
```diff
@@ -5,17 +5,18 @@
  * @version 2022-06-25
  */
 
+#include "cmm/Types.h"
```
Comment (hockeyhurd) [inline src/VariableNode.cpp]: Use angle brackets.

File: src/platform/PlatformLLVM.cpp [hunk 2]
```diff
@@ -280,17 +282,30 @@ namespace cmm
         const auto& fromCType = node.getExpression()->getDatatype();
         const auto& toCType = node.getDatatype();
 
-        if ((fromCType.isInt() && toCType.type == EnumCType::ENUM) ||
-            (fromCType.type == EnumCType::ENUM && toCType.isInt()))
+        // TODO (Nick): Rewrite this section to see if we actually need to cast,
```
Comment (hockeyhurd) [inline src/platform/PlatformLLVM.cpp]: Resolve TODO or update comment as needed.

**Review by hockeyhurd — COMMENTED** [review]
Looks good. See the couple of review comments.

File: src/VariableNode.cpp (hunk 1 above)
Comment (hockeyhurd) [reply src/VariableNode.cpp]: Resolved in commit 0a1dcbc55860a01c2e93ebc83e87e754309a55d5.

File: src/platform/PlatformLLVM.cpp (hunk 2 above)
Comment (hockeyhurd) [reply src/platform/PlatformLLVM.cpp]: Resolved in commit 0a1dcbc55860a01c2e93ebc83e87e754309a55d5.
