### PR TITLE
Issue 42 unary expressions

### LINKED ISSUE #42: Some unary expressions failing
It appears unary expressions such as '+' and '-' work well for numbers.  However, the current implementation does not working for function calls or variables (see examples below).

`a = 123.0 + -func()`
`a = 123.0 + -func`

### PR DESCRIPTION
**Pull request by hockeyhurd**
Mostly a fix for unary operators as well as adding support for increment and decrement operators.

### CODE REVIEW

File: src/UnaryOpNode.cpp [hunk 1]
```diff
@@ -0,0 +1,149 @@
...
+// Our includes
+#include <cmm/UnaryOpNode.h>
+#include <cmm/Token.h>
+
+// std includes
+#include <unordered_map>
+
+namespace cmm
+{
+    static std::unordered_map<std::string, EnumUnaryOpType> opTypeTable;
```
Comment (hockeyhurd) [inline src/UnaryOpNode.cpp:17]: Let's move this to a static member variable to UnaryOpNode class.

File: src/visit/Analyzer.cpp [hunk 2]
```diff
@@ -523,6 +536,24 @@ namespace cmm
...
+        if (node.hasExpression())
+        {
+            auto* expression = node.getExpression();
+            expression->accept(this);
+
+            if (node.getOpType() == EnumUnaryOpType::ADDRESS_OF && expression->getType() != NodeType::VARIABLE)
+            {
+                const char* message = "Expected a variable expression prior to attempting to take the address of it";
+                reporter.error(message, node.getLocation());
+                return VisitorResult();
```
Comment (hockeyhurd) [inline src/visit/Analyzer.cpp]: Redundant return statement can be removed.

File: src/visit/Dump.cpp [hunk 3]
```diff
@@ -452,6 +452,26 @@ namespace cmm
...
+        printIndentation();
+        printNode(node);
+        printNewLine();
+
+        increaseIntentation();
+        printIndentation();
+        std::cout << "UnaryOpType: " << toString(node.getOpType());
+        printNewLine();
+
+        auto* expression = node.getExpression();
```
Comment (hockeyhurd) [inline src/visit/Dump.cpp]: Add check for `node.hasExpression()`

**Review by hockeyhurd — COMMENTED** [review]
See review comments.  Good to merge otherwise.

File: src/UnaryOpNode.cpp (hunk 1 above)
Comment (hockeyhurd) [reply src/UnaryOpNode.cpp:17]: Never mind, not applicable to the class.

File: src/visit/Analyzer.cpp (hunk 2 above)
Comment (hockeyhurd) [reply src/visit/Analyzer.cpp]: Resolved in commit f2e8f04.

File: src/visit/Dump.cpp (hunk 3 above)
Comment (hockeyhurd) [reply src/visit/Dump.cpp]: Resolved in commit f2e8f04.

**Comment by hockeyhurd** [comment]
Issue #42 is considered resolved with the merge of this PR.
