### PR TITLE
Fix issue #86

### LINKED ISSUE #86: Incorrect Datatype with Pointers
I stumbled upon an issue where the following code tries to allocate a struct rather than the expected pointer to a struct.  I believe the cause is due to an over-usage of PlatformLLVM::resolveDatatype rather than using the more appropriate printDatatype, which will include the '*' as needed.

See [pastebin](https://pastebin.com/59Qj1bM5)

### PR DESCRIPTION
**Pull request by hockeyhurd**
Resolved initial issue and uncovered more :) ...

This goes to show, we need a proper regression testing on generated LLVM code. Instead of fixing all issues under this PR, will shift focus on that separately.

### CODE REVIEW

File: src/visit/Analyzer.cpp [hunk 1]
```diff
@@ -1285,6 +1297,38 @@ namespace cmm
...
+            return false;
+        }
+
+        const ExpressionNode* nodeToTest = node;
+
+        if (nodeType == EnumNodeType::DEREF)
+        {
+            const DerefNode* derefNode = static_cast<const DerefNode*>(node);
+
+            // TODO @@@: Need to consider multiple DerefNode and needing to 'dig' to the bottom VariableNode.
```
Comment (hockeyhurd) [inline src/visit/Analyzer.cpp]: Resolved TODO

File: src/visit/Analyzer.cpp [hunk 2]
```diff
@@ -1285,6 +1297,38 @@ namespace cmm
...
+            if (derefNode->getExpression()->getType() != EnumNodeType::VARIABLE)
+            {
+                return false;
+            }
+
+            // Must be VariableNode!
+            nodeToTest = derefNode->getExpression();
+        }
+
+        // const VariableNode* varNode = static_cast<const VariableNode*>(node);
```
Comment (hockeyhurd) [inline src/visit/Analyzer.cpp]: Clean-up

**Review by hockeyhurd — COMMENTED** [review]
See review comments.
